services:
  book_bot_back_service:
    container_name: 'book_bot_back'
    build:
      context: .
    ports:
      - "8001:8000"
    networks:
      - my_network
    env_file:
      - .env

  book_bot_db_service:
    container_name: 'book_bot_db'
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "6432:5432"
    volumes:
      - pg-book_bot-data:/var/lib/postgresql/data
    networks:
      - my_network


volumes:
  pg-book_bot-data:


networks:
  my_network:
    external: true
